services:
  - type: web
    name: estebankito
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn proyecto.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: proyecto.settings.settings
